name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Install compiler
        run: sudo apt-get install build-essential

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2.3.0
        with:
          poetry-version: '1.5.1'

      - name: Export dependencies
        run: poetry export --with docs --without-hashes --output requirements.txt

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUIREMENTS: requirements.txt